# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brain < Formula
  desc "Local Brain - A personal knowledge management CLI tool"
  homepage "https://github.com/SanderMoon/local-brain"
  version "1.1.0"
  license "MIT"

  depends_on "bat" => :optional
  depends_on "fzf" => :optional
  depends_on "jq" => :optional
  depends_on "ripgrep" => :optional
  depends_on "syncthing" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.1.0/local-brain_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "b8e9d35a1ea813c660420ee302bbb7e0b20dd6069716b4585c54757092cce907"

      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.1.0/local-brain_1.1.0_Darwin_arm64.tar.gz"
      sha256 "57eaffe867e8093ee2e06ca427cfe18d591ecf622cfe48cb6b4ae8b21c30ddc6"

      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.1.0/local-brain_1.1.0_Linux_x86_64.tar.gz"
      sha256 "01298dd6bcbcea9fa1509757edda33a5044df101e2a12a6b9df3b6c96fb0255f"
      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.1.0/local-brain_1.1.0_Linux_arm64.tar.gz"
      sha256 "072b5582f0f212de923a87ff49dad47ab2fc7c1558e5a4785c9e223a1b48e684"
      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Local Brain:

      1. Initialize your first brain:
         brain init

      2. Add the brain-prompt.sh to your shell config:
         echo 'source $(brew --prefix)/share/brain/brain-prompt.sh' >> ~/.zshrc

      3. Install dependencies (if not already installed):
         brew install ripgrep fzf bat syncthing jq

      For more information, visit: https://github.com/SanderMoon/local-brain
    EOS
  end

  test do
    system "#{bin}/brain", "--version"
  end
end
