# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brain < Formula
  desc "Local Brain - A personal knowledge management CLI tool"
  homepage "https://github.com/SanderMoon/local-brain"
  version "1.11.1"
  license "MIT"

  depends_on "bat" => :optional
  depends_on "fzf"
  depends_on "jq" => :optional
  depends_on "ripgrep"
  depends_on "syncthing" => :optional
  depends_on "tmux" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.11.1/local-brain_1.11.1_Darwin_x86_64.tar.gz"
      sha256 "d65346cc847c8b984db7d585b81025bb7480ca534e84e4c15587974493a5a225"

      def install
        bin.install "brain"
        bin.install "brain-mcp"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.11.1/local-brain_1.11.1_Darwin_arm64.tar.gz"
      sha256 "562b576c777ea30b51a3c07793e00e70617e2941e61c40c9c221bb15b6d5c88b"

      def install
        bin.install "brain"
        bin.install "brain-mcp"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.11.1/local-brain_1.11.1_Linux_x86_64.tar.gz"
      sha256 "1393ad41f80f47db9e1d224e82761e84e66b59fc0e1a728bf09940a6964cf133"
      def install
        bin.install "brain"
        bin.install "brain-mcp"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.11.1/local-brain_1.11.1_Linux_arm64.tar.gz"
      sha256 "8d5869e4423e1fe41757785e15f3fa783695ef4b1cad06ec4b4259019624c758"
      def install
        bin.install "brain"
        bin.install "brain-mcp"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Local Brain:

      1. Initialize your first brain:
         brain init

      2. Add the brain-prompt.sh to your shell config:
         echo 'source $(brew --prefix)/share/brain/brain-prompt.sh' >> ~/.zshrc

      3. Optional: Enable Claude Desktop integration
         The MCP server (brain-mcp) is installed for Claude Desktop integration.
         Add to ~/Library/Application Support/Claude/claude_desktop_config.json:
         {
           "mcpServers": {
             "local-brain": {
               "command": "#{bin}/brain-mcp"
             }
           }
         }

      4. Optional enhancements:
         brew install tmux bat syncthing jq

      For more information, visit: https://github.com/SanderMoon/local-brain
    EOS
  end

  test do
    system "#{bin}/brain", "--version"
  end
end
