# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brain < Formula
  desc "Local Brain - A personal knowledge management CLI tool"
  homepage "https://github.com/SanderMoon/local-brain"
  version "1.3.0"
  license "MIT"

  depends_on "bat" => :optional
  depends_on "fzf"
  depends_on "jq" => :optional
  depends_on "ripgrep"
  depends_on "syncthing" => :optional
  depends_on "tmux" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.3.0/local-brain_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "44f30aa7c70f62c8b7b8e368af74e19a97e00d9dd2f7014092565ed2dd1b9dd5"

      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.3.0/local-brain_1.3.0_Darwin_arm64.tar.gz"
      sha256 "70aa32b184f8cd3f83b0173137f3f4909b6e1c56b5994bcdca15ecc7af5c7975"

      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.3.0/local-brain_1.3.0_Linux_x86_64.tar.gz"
      sha256 "eb1728f7837d1c842b678e3e30f7a6b5fe43516114f16709464ec6be4d74f8df"
      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SanderMoon/local-brain/releases/download/v1.3.0/local-brain_1.3.0_Linux_arm64.tar.gz"
      sha256 "839fc59815aa70f5ec6690f504129c6216f0af0553938416142120a520fe36e4"
      def install
        bin.install "brain"
        # Install the shell prompt helper
        (share/"brain").install "lib/brain-prompt.sh"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Local Brain:

      1. Initialize your first brain:
         brain init

      2. Add the brain-prompt.sh to your shell config:
         echo 'source $(brew --prefix)/share/brain/brain-prompt.sh' >> ~/.zshrc

      3. Optional enhancements:
         brew install tmux bat syncthing jq

      For more information, visit: https://github.com/SanderMoon/local-brain
    EOS
  end

  test do
    system "#{bin}/brain", "--version"
  end
end
